//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPOPSOFT.Controls {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GongSi {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GongSi() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CNPOPSOFT.Controls.GongSi", typeof(GongSi).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap a1 {
            get {
                object obj = ResourceManager.GetObject("a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a10 {
            get {
                object obj = ResourceManager.GetObject("a10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a11 {
            get {
                object obj = ResourceManager.GetObject("a11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a12 {
            get {
                object obj = ResourceManager.GetObject("a12", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a13 {
            get {
                object obj = ResourceManager.GetObject("a13", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a14 {
            get {
                object obj = ResourceManager.GetObject("a14", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a15 {
            get {
                object obj = ResourceManager.GetObject("a15", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a16 {
            get {
                object obj = ResourceManager.GetObject("a16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a17 {
            get {
                object obj = ResourceManager.GetObject("a17", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a18 {
            get {
                object obj = ResourceManager.GetObject("a18", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a19 {
            get {
                object obj = ResourceManager.GetObject("a19", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a2 {
            get {
                object obj = ResourceManager.GetObject("a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a20 {
            get {
                object obj = ResourceManager.GetObject("a20", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a3 {
            get {
                object obj = ResourceManager.GetObject("a3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a4 {
            get {
                object obj = ResourceManager.GetObject("a4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a5 {
            get {
                object obj = ResourceManager.GetObject("a5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a6 {
            get {
                object obj = ResourceManager.GetObject("a6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a7 {
            get {
                object obj = ResourceManager.GetObject("a7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a8 {
            get {
                object obj = ResourceManager.GetObject("a8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap a9 {
            get {
                object obj = ResourceManager.GetObject("a9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] asi {
            get {
                object obj = ResourceManager.GetObject("asi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bbi {
            get {
                object obj = ResourceManager.GetObject("bbi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bdt {
            get {
                object obj = ResourceManager.GetObject("bdt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] bias {
            get {
                object obj = ResourceManager.GetObject("bias", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] boll {
            get {
                object obj = ResourceManager.GetObject("boll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] brar {
            get {
                object obj = ResourceManager.GetObject("brar", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] btx {
            get {
                object obj = ResourceManager.GetObject("btx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] btxpbx {
            get {
                object obj = ResourceManager.GetObject("btxpbx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cci {
            get {
                object obj = ResourceManager.GetObject("cci", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] cr {
            get {
                object obj = ResourceManager.GetObject("cr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] db6 {
            get {
                object obj = ResourceManager.GetObject("db6", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dma {
            get {
                object obj = ResourceManager.GetObject("dma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] dmi {
            get {
                object obj = ResourceManager.GetObject("dmi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] emv {
            get {
                object obj = ResourceManager.GetObject("emv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] expma {
            get {
                object obj = ResourceManager.GetObject("expma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fs {
            get {
                object obj = ResourceManager.GetObject("fs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fs2 {
            get {
                object obj = ResourceManager.GetObject("fs2", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] fsl {
            get {
                object obj = ResourceManager.GetObject("fsl", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] kdj {
            get {
                object obj = ResourceManager.GetObject("kdj", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ma {
            get {
                object obj = ResourceManager.GetObject("ma", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] macd {
            get {
                object obj = ResourceManager.GetObject("macd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mike {
            get {
                object obj = ResourceManager.GetObject("mike", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] mtm {
            get {
                object obj = ResourceManager.GetObject("mtm", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] obv {
            get {
                object obj = ResourceManager.GetObject("obv", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] pbx {
            get {
                object obj = ResourceManager.GetObject("pbx", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] psy {
            get {
                object obj = ResourceManager.GetObject("psy", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] roc {
            get {
                object obj = ResourceManager.GetObject("roc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] rsi {
            get {
                object obj = ResourceManager.GetObject("rsi", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] sin {
            get {
                object obj = ResourceManager.GetObject("sin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] trix {
            get {
                object obj = ResourceManager.GetObject("trix", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] twr {
            get {
                object obj = ResourceManager.GetObject("twr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] vol {
            get {
                object obj = ResourceManager.GetObject("vol", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] vr {
            get {
                object obj = ResourceManager.GetObject("vr", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] wr {
            get {
                object obj = ResourceManager.GetObject("wr", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
